---
 - name: install additional packages for encoder role
   apt: name={{ item }} state=latest
   with_items:
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-tools
    - libgstreamer1.0-0
    - python3
    - python3-gi
    - python3-yaml
    - python3-paho-mqtt
    - gir1.2-gstreamer-1.0
    - gir1.2-gst-plugins-base-1.0
    - rlwrap
    - desktopvideo
    - decklink-debugger
