---
  # directories & code
  - name: create sdi-recorder directories (root)
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/sdi-recorder

  - name: create backup-recorder group
    user: name=backup-recorder state=present system=true

  - name: create backup-recorder user
    user: name=backup-recorder group=backup-recorder state=present system=true

  - name: create sdi-recorder directories (user)
    file: dest=/video/sdi-backup/{{ room_fahrplan_name | lower | replace(' ', '') }}/{{ item.name }} state=directory
          owner=backup-recorder group=backup-recorder
    with_items: "{{ sdi_recorder }}"


  # sdi-recorder services
  - name: create sdi-recorder scripts
    template: src="sdi-recorder/sdi-recorder.sh.j2"
              dest="/opt/sdi-recorder/sdi-{{ item.name }}-recorder.sh"
              mode=0755 owner=root group=root
    with_items: "{{ sdi_recorder }}"

  - name: create sdi-recorder systemd-unit
    template: src="systemd-units/sdi-recorder.service.j2"
              dest="/etc/systemd/system/sdi-{{ item.name }}-recorder.service"
              mode=0644 owner=root group=root
    with_items: "{{ sdi_recorder }}"

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable & start sdi-recorder service
    service: name=sdi-{{ item.name }}-recorder.service
             enabled=yes
             state=started
    with_items: "{{ sdi_recorder }}"
